# Generated by Django 4.2.9 on 2026-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snacks", "Snacks"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ingredients", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.CharField(
                        choices=[("uniliv", "UNILIV"), ("huddle", "HUDDLE")],
                        default="uniliv",
                        max_length=20,
                    ),
                ),
                ("is_dal", models.BooleanField(default=False)),
                ("is_star", models.BooleanField(default=False)),
                ("is_aloo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Dishes",
                "ordering": ["-created_at"],
                "unique_together": {("dish_name", "meal_type", "brand")},
            },
        ),
    ]
