# Generated by Django 4.2.9 on 2026-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_scheduledmeal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="scheduledmeal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledmeal",
            name="week_number",
            field=models.PositiveSmallIntegerField(help_text="1–4"),
        ),
    ]
