# Generated by Django 4.2.9 on 2026-04-17 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0003_alter_dish_options_alter_scheduledmeal_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("property", "Property Dashboard"),
                            ("food", "Food Dashboard"),
                            ("admin", "Both Dashboards"),
                        ],
                        default="food",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("uniliv", "UNILIV"), ("huddle", "HUDDLE")],
                        default="uniliv",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
