# Generated by Django 4.2.9 on 2026-04-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                ("unit_lead", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Evening Snacks", "Evening Snacks"),
                            ("Dinner", "Dinner"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ordered", "Ordered"),
                            ("Dispatched", "Dispatched"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Ordered",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kg"),
                            ("grams", "Grams"),
                            ("litres", "Litres"),
                            ("ml", "ML"),
                            ("pieces", "Pieces"),
                            ("packets", "Packets"),
                            ("dozen", "Dozen"),
                            ("boxes", "Boxes"),
                        ],
                        default="kg",
                        max_length=20,
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fo_items",
                        to="dashboard.foodorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_otp", models.CharField(max_length=6)),
                (
                    "dispatched_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("otp_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof_file",
                    models.FileField(
                        blank=True, null=True, upload_to="dispatch_proofs/"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="dashboard.foodorder",
                    ),
                ),
            ],
        ),
    ]
