# Generated by Django 4.2.9 on 2026-04-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_foodorder_foodorderitem_fooddispatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooddispatch",
            name="proof_file",
        ),
    ]
