# Generated by Django 4.2.9 on 2026-05-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_fooddispatch_proof_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoodDispatch",
        ),
    ]
